blank_issues_enabled: false
contact_links:
  - name: ğŸ Found a bug or Suggest new feature ?
    url: https://github.com/Huseyinnurbaki/crypto-watchdog/issues/new/choose
    about: Please file an issue in the crypto-watchdog Github repo.
